/**
 * The chrome sounds the player can make.
 *
 * Chrome sounds are the player's feel, not content — the same kind of thing as
 * `PAGE` in `storyPageFrame.ts`, which is the story's look. They are declared
 * here rather than in a manifest because a manifest carrying `sfx: "star.wav"`
 * would be a renderer decision inside an engine-neutral contract, which
 * invariant 2 forbids (`docs/plans/ideas/audio.md`, "The three populations").
 *
 * The files are generated by `scripts/generate-chrome-sounds.mjs` and verified
 * by `scripts/check-audio-assets.mjs`, which asserts this list and the
 * generator's own list name exactly the same sounds. Adding a sound in one
 * place and not the other fails `pnpm check` rather than shipping a silent
 * event or a file nothing plays.
 */
export const SOUND_IDS = [
  "tap",
  "select",
  "back",
  "correct",
  "wrong",
  "page-turn",
  "star",
  "chest-appear",
  "chest-open",
  "reveal",
  "fanfare",
  "unlock"
] as const;

/**
 * Derived from the list rather than declared beside it, so the type and the
 * thing that loads the files cannot disagree.
 */
export type SoundId = (typeof SOUND_IDS)[number];

/**
 * Absolute, matching how the rest of the player's public assets are addressed
 * (`/vocabulary/…`, `/world/…`).
 */
export const soundUrl = (id: SoundId): string => `/sfx/${id}.wav`;
