/**
 * Importer for the profile avatars.
 *
 * Kept in the repository for the same reason as `import-vocabulary-images.mjs`
 * and `import-world-art.mjs`: it *is* the provenance record. Re-running it
 * reproduces every committed file, and the document it writes names the exact
 * upstream URL each one came from.
 *
 *   node scripts/import-avatars.mjs
 *
 * The source is Microsoft's Fluent Emoji, under the MIT licence — permissive,
 * and requiring no credit line anywhere a user can see. The 3D style is the
 * chunky, toy-like one; it reads as a character to a three-year-old rather than
 * as an icon.
 *
 * This runs at import time and its output is committed. Nothing here is ever
 * fetched while a child is playing: no request for an avatar leaves the device.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import sharp from "sharp";

const OUTPUT_DIR = "apps/player-web/public/avatars";

/*
 * Smaller than the 512 the world art uses. An avatar is drawn at 56px in the
 * corner and about 44px in a menu row, so 256 already carries a 4× display
 * without the file being mostly detail nobody sees.
 */
const EDGE = 256;
const QUALITY = 82;

const LICENCE = "MIT";
const UPSTREAM = "https://github.com/microsoft/fluentui-emoji";

/**
 * The catalogue, keyed by the id the player stores.
 *
 * Animals rather than faces: a child picking a fox is choosing a character,
 * with none of the questions that choosing a face for a child would raise.
 */
const AVATARS = [
  { id: "zorro", emoji: "Fox" },
  { id: "panda", emoji: "Panda" },
  { id: "gato", emoji: "Cat face" },
  { id: "perro", emoji: "Dog face" },
  { id: "leon", emoji: "Lion" },
  { id: "rana", emoji: "Frog" },
  { id: "buho", emoji: "Owl" },
  { id: "pinguino", emoji: "Penguin" },
  { id: "tortuga", emoji: "Turtle" },
  { id: "unicornio", emoji: "Unicorn" },
  { id: "koala", emoji: "Koala" },
  { id: "tigre", emoji: "Tiger" }
];

function sourceUrl(emoji) {
  const slug = emoji.toLowerCase().replaceAll(" ", "_");
  const directory = encodeURIComponent(emoji);
  return (
    "https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/" +
    `${directory}/3D/${slug}_3d.png`
  );
}

async function download(url) {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`${url} responded ${response.status}`);
  }
  return Buffer.from(await response.arrayBuffer());
}

await mkdir(OUTPUT_DIR, { recursive: true });

const imported = [];
for (const { id, emoji } of AVATARS) {
  const url = sourceUrl(emoji);
  const source = await download(url);

  /* Trimmed first so the whole budget is spent on the animal rather than on
     the transparent margin the upstream sprite is padded with. */
  const output = await sharp(source)
    .trim()
    .resize({ width: EDGE, height: EDGE, fit: "inside", withoutEnlargement: true })
    .webp({ quality: QUALITY })
    .toBuffer();

  const destination = join(OUTPUT_DIR, `${id}.webp`);
  await writeFile(destination, output);

  const { width, height } = await sharp(output).metadata();
  imported.push({ id, emoji, url, bytes: output.length, width, height });
  process.stdout.write(
    `${emoji} → ${destination} (${width}×${height}, ` +
      `${Math.round(output.length / 1024)} kB)\n`
  );
}

const total = imported.reduce((sum, each) => sum + each.bytes, 0);

const rows = imported
  .map(
    ({ id, emoji, url, bytes }) =>
      `| \`${id}.webp\` | ${emoji} | [source](${url}) | ${Math.round(bytes / 1024)} kB |`
  )
  .join("\n");

await writeFile(
  join(OUTPUT_DIR, "PROVENANCE.md"),
  `# Profile avatar provenance

Generated by \`scripts/import-avatars.mjs\`. Re-run it to reproduce every file
here; do not add pictures by hand.

## Source and rights

Imported from [Microsoft Fluent Emoji](${UPSTREAM}), 3D style, which is
published under the **${LICENCE}** licence. That licence permits commercial use
and redistribution, and requires only that the licence text travel with the
work — it asks for no credit line in the product interface.

Unlike \`public/vocabulary\`, every file here records the exact upstream URL it
was built from, so an individual picture's origin is recoverable and a licence
question about any one of them can be answered without re-auditing the set.

No picture contains or depicts child data. These are cartoon animals, chosen so
that a child picks a character rather than a face.

## Processing

Each source PNG was trimmed to its subject, resized to fit within ${EDGE}×${EDGE}
without enlargement, and re-encoded as WebP at quality ${QUALITY}, preserving
transparency. Trimming precedes the resize so the budget is spent on the animal
rather than on the transparent padding the upstream sprites carry.

Total: ${Math.round(total / 1024)} kB across ${imported.length} files.

## Files

| Committed | Emoji | Source | Size |
|---|---|---|---|
${rows}
`
);

process.stdout.write(
  `\n${imported.length} avatars, ${Math.round(total / 1024)} kB total\n`
);
