import {
  childRecordId,
  mediaAssetId,
  type ChildRecord
} from "@lectoemocion/domain";

function syntheticChild(
  id: string,
  displayName: string,
  verifiedInitial: string
): ChildRecord {
  return {
    id: childRecordId(id),
    displayName,
    verifiedInitial,
    photoAssetId: mediaAssetId(`avatar-${id}`),
    pronunciationAssetId: mediaAssetId(`silent-${id}`)
  };
}

/**
 * A class that does not exist, for developing and testing against.
 *
 * Every name is invented and every asset is generated by
 * `scripts/generate-synthetic-cast.mjs`. AGENTS.md forbids real child data in
 * fixtures, and this list is the reason that rule needs writing down: `name-book`
 * cannot be built or seen at all without a roster, so something has to stand in.
 *
 * It is deliberately awkward in the ways a real class is, because the book of
 * names is sorted and grouped and each of these is a case that would otherwise
 * only be found by a teacher:
 *
 * - three children share `A`, so a page holding several names is exercised;
 * - `Álex` is accented and must sort under `A` while keeping its accent;
 * - `Ñuria` must land after `Nora` rather than after `Zara`;
 * - `Chema` is verified under `CH`, so a page keyed on a digraph exists and a
 *   grouping that used the first character of the name would file them wrong.
 */
export const syntheticClass: readonly ChildRecord[] = [
  syntheticChild("ana", "Ana", "A"),
  syntheticChild("alex", "Álex", "A"),
  syntheticChild("aitor", "Aitor", "A"),
  syntheticChild("bruno", "Bruno", "B"),
  syntheticChild("carla", "Carla", "C"),
  syntheticChild("chema", "Chema", "CH"),
  syntheticChild("diego", "Diego", "D"),
  syntheticChild("elena", "Elena", "E"),
  syntheticChild("fatima", "Fátima", "F"),
  syntheticChild("gael", "Gael", "G"),
  syntheticChild("hugo", "Hugo", "H"),
  syntheticChild("irene", "Irene", "I"),
  syntheticChild("julia", "Julia", "J"),
  syntheticChild("luna", "Luna", "L"),
  syntheticChild("mateo", "Mateo", "M"),
  syntheticChild("nora", "Nora", "N"),
  syntheticChild("nuria", "Ñuria", "Ñ"),
  syntheticChild("rocio", "Rocío", "R"),
  syntheticChild("sara", "Sara", "S"),
  syntheticChild("zara", "Zara", "Z")
];
